(function(g){var window=this;'use strict';var Ti=function(R){R.publish("cardstatechange",R.LW()&&R.VW()?1:0)},dW=function(R,l){var y=g.KX(l),f=y?l:arguments;
for(y=y?0:1;y<f.length;y++){if(R==null)return;R=R[f[y]]}return R},koO=function(R){var l=g.Yb(R);
R=g.l4(R);return new g.Sv(l.x,l.y,R.width,R.height)},DdU=function(R,l,y){var f=f===void 0?{}:f;
var A;return A=g.PW(R,l,function(){g.uJ(A);y.apply(R,arguments)},f)},zi=function(R){R=g.s5(R);
delete rW[R];g.oL(rW)&&v7&&v7.stop()},JWZ=function(){v7||(v7=new g.Vg(function(){Z$K()},20));
var R=v7;R.isActive()||R.start()},Z$K=function(){var R=g.mU();
g.RL(rW,function(l){gQ5(l,R)});
g.oL(rW)||JWZ()},wW=function(R,l,y,f){g.HJ.call(this);
if(!Array.isArray(R)||!Array.isArray(l))throw Error("Start and end parameters must be arrays");if(R.length!=l.length)throw Error("Start and end points must be the same length");this.X=R;this.V=l;this.duration=y;this.J=f;this.coords=[];this.progress=this.D=0;this.Y=null},gQ5=function(R,l){l<R.startTime&&(R.endTime=l+R.endTime-R.startTime,R.startTime=l);
R.progress=(l-R.startTime)/(R.endTime-R.startTime);R.progress>1&&(R.progress=1);R.D=1E3/(l-R.Y);R.Y=l;VSS(R,R.progress);R.progress==1?(R.Z=0,zi(R),R.onFinish(),R.TA()):R.isPlaying()&&R.Bb()},VSS=function(R,l){typeof R.J==="function"&&(l=R.J(l));
R.coords=Array(R.X.length);for(var y=0;y<R.X.length;y++)R.coords[y]=(R.V[y]-R.X[y])*l+R.X[y]},C45=function(R,l){g.gJ.call(this,R);
this.coords=l.coords;this.x=l.coords[0];this.y=l.coords[1];this.z=l.coords[2];this.duration=l.duration;this.progress=l.progress;this.fps=l.D;this.state=l.Z},xd=function(R,l,y,f,A){wW.call(this,l,y,f,A);
this.element=R},qJU=function(R,l,y,f,A){if(l.length!=2||y.length!=2)throw Error("Start and end points must be 2D");
xd.call(this,R,l,y,f,A)},tSU=function(R){return Math.pow(R,3)},YJK=function(R){return 3*R*R-2*R*R*R},MSD=function(R){g.p.call(this);
this.X=R||window;this.Z=[]},I6=function(R){return R.baseUrl||null},Nx=function(R,l){return g.bs(g.L$(R,l),function(y){return!!y})},RAU=function(R,l,y){function f(Bi){var ar=Bi.hovercardButton;
if(!ar)return null;ar=ar.subscribeButtonRenderer;if(!ar)return null;var nk=K(ar.unsubscribedButtonText),Y=K(ar.subscribedButtonText);if(ar.subscribed){var Pi=K(ar.subscriberCountWithUnsubscribeText);var wq=K(ar.subscriberCountText)}else Pi=K(ar.subscriberCountText),wq=K(ar.subscriberCountWithSubscribeText);var Rt=null;if(Bi.signinEndpoint){Rt=dW(Bi,"signinEndpoint","webNavigationEndpointData","url");if(!Rt){var pX,O5;Rt=(O5=g.k((pX=ar.signInEndpoint)==null?void 0:pX.commandMetadata,g.Qn))==null?void 0:
O5.url}if(!Rt)return null}return nk&&(Y||Rt)?{subscribed:ar.subscribed,subscribeText:nk,subscribeCount:Pi,unsubscribeText:Y,unsubscribeCount:wq,enabled:ar.enabled,signinUrl:Rt,classic:Bi.useClassicSubscribeButton}:null}
function A(Bi){if(Bi){var ar=[],nk=Bi.videoId;nk&&ar.push("v="+nk);(nk=Bi.playlistId)&&ar.push("list="+nk);(Bi=Bi.startTimeSeconds)&&ar.push("t="+Bi);return"/watch?"+ar.join("&")}}
function K(Bi){if(!Bi)return null;var ar=Bi.simpleText;return ar?ar:Bi.runs?g.L$(Bi.runs,function(nk){return nk.text}).join(""):null}
l=l.endscreenElementRenderer;if(!l)return null;var G=l.style,B=l.endpoint||{},H=null,n=null,m=!1,h=null,c=null,E=null,W=null,Q=!1,e=null,r=null,d=null,z=null,N=null,D=null;if(G==="VIDEO")g.k(B,g.wp)?H=g.k(B,g.wp).url:(D=g.k(B,g.mh),H=A(D)),n=!1,h=R,l.thumbnailOverlays?(m=l.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,c=K(m.text),m=m.style==="LIVE"):c=K(l.videoDuration);else if(G==="PLAYLIST")g.k(B,g.wp)?H=g.k(B,g.wp).url:(D=g.k(B,g.mh),H=A(D)),n=!1,h=R,E=K(l.playlistLength);else if(G===
"CHANNEL"){if(Q=dW(B,"browseEndpoint","browseId"))W=Q,H="/channel/"+W;n=!1;h="new";(Q=!!l.isSubscribe)?e=f(l):r=K(l.subscribersText)}else G==="WEBSITE"?((d=dW(B,"urlEndpoint","url"))&&(H=d),n=!0,h="new",d=l.icon.thumbnails[0].url):G==="CREATOR_MERCHANDISE"&&(l.productPrice&&(z=K(l.productPrice)),l.additionalFeesText&&(N=K(l.additionalFeesText)),(n=dW(B,"urlEndpoint","url"))&&(H=n),n=!0,h="new");R=dW(l,"title","accessibility","accessibilityData","label");var t=l.endpoint?l.endpoint.clickTrackingParams:
null,C="";if(l.metadata){var Ac=K(l.metadata);Ac&&(C=Ac)}return{id:"element-"+y,type:G,title:K(l.title),metadata:C,callToAction:K(l.callToAction),Cg:l.image,iconUrl:d,left:Number(l.left),width:Number(l.width),top:Number(l.top),aspectRatio:Number(l.aspectRatio),startMs:Math.floor(Number(l.startMs)),endMs:Math.floor(Number(l.endMs)),videoDuration:c,Ed:m,playlistLength:E,channelId:W,subscribeButton:e,subscribersText:r,isSubscribe:Q,targetUrl:H||null,Cu:n,sessionData:t?{itct:t}:null,QTx:h,Z5:R?R:null,
isPlaceholder:l.isPlaceholder,impressionUrls:Nx(l.impressionUrls||[],I6),Lu:Nx(l.hovercardShowUrls||[],I6),clickUrls:Nx(B.loggingUrls||[],I6),visualElement:g.Ll(l.trackingParams),productPrice:z,additionalFeesText:N,watchEndpoint:D||null}},llO=function(R,l){var y={startMs:Math.floor(Number(R.startMs)),
impressionUrls:Nx(R.impressionUrls||[],I6),elements:Nx(R.elements||[],function(f,A){return RAU(l,f,A)})};
R.trackingParams&&(y.visualElement=g.Ll(R.trackingParams));return y},yar=function(R){g.Fc.call(this,R);
this.Y=this.endscreen=null;this.X={};this.D={};this.J=this.L=null;this.W=[];this.Z=null;this.LX=!0;this.V=0;R=R.U();this.B=g.CI(R)||g.tu(R);this.events=new g.QW(this);g.U(this,this.events);this.events.N(this.player,g.Vx("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.Cd("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.ub);this.events.N(window,"focus",this.e0E);this.load();var l=g.ho("STYLE");(g.Ao("HEAD")[0]||document.body).appendChild(l);this.addOnDisposeCallback(function(){g.Ot(l)});
l.sheet&&(l.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),l.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},flr=function(R){return R.player.getVideoData().nJ?"current":R.B?"new":"current"},p7=function(R){return R.player.U().playerStyle==="creator-endscreen-editor"},AaU=function(R){var l=R.player.getVideoData(),y=l.videoId;
R.Y&&R.Y.abort();y={method:"POST",onFinish:function(A){var K=R.Y=null;A.status===200&&(A=A.responseText,A.substring(0,3)===")]}"&&(A=A.substring(3),K=JSON.parse(A),K=llO(K,flr(R))));Uk(R,K)},
urlParams:{v:y},withCredentials:!0};R.B&&(y.urlParams.ptype="embedded");var f=l.xZ;f&&(y.postParams={ad_tracking:f});if(l=g.Xu9(l))if(l=g.sp(l),l=g.AM(l))R.Y=g.Qt(l,y)},Uk=function(R,l,y){y=y===void 0?!0:y;
R.player.yb("creatorendscreen");R.L&&(R.L.dispose(),R.L=null,R.J.dispose(),R.J=null);for(var f=g.u(Object.values(R.X)),A=f.next();!A.done;A=f.next())A.value.dispose();R.X={};R.D={};R.W.length>0&&(R.W.forEach(function(B){B.dispose()}),R.W.length=0);
R.Z&&(g.G8(R.Z,"ytp-ce-element-show"),R.Z.setAttribute("aria-hidden","true"));R.V=0;if((R.endscreen=l)&&l.elements){y&&KWd(R);y=[];f=new g.Jq(l.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});y.push(f);R.player.U().X||(R.L=new g.Z({T:"div",j:"ytp-ce-shadow"}),g.kT(R.player,R.L.element,4),R.J=new g.MF(R.L,200));for(f=0;f<l.elements.length;++f){A=l.elements[f];var K=Gmr(R,A);if(K){R.X[A.id]=K;R.D[A.id]=A;g.kT(R.player,K.element,4);var G=new g.Jq(A.startMs,A.endMs,{id:"ytp-ce-element-"+
A.id,namespace:"creatorendscreen"});y.push(G);alA(R,K,A)}else g.dP(new g.JD("buildEndscreenElement null",A))}R.player.OS(y);R.ub()}},KWd=function(R){var l=g.ir(),y=g.Py();
y&&l&&R.endscreen.visualElement&&g.qM(g.k$)(void 0,y,l,R.endscreen.visualElement)},Gmr=function(R,l){var y=null;
switch(l.type){case "VIDEO":R={T:"div",QL:["ytp-ce-element","ytp-ce-video"],K:{tabindex:"0","aria-label":l.Z5||"","aria-hidden":"true"},S:[{T:"div",j:"ytp-ce-element-shadow"},{T:"div",j:"ytp-ce-covering-image",K:S$(l)},{T:"div",j:"ytp-ce-covering-shadow-top"},{T:"a",j:"ytp-ce-covering-overlay",K:{href:j$(R,l.targetUrl),tabindex:"-1"},S:[{T:"div",QL:["ytp-ce-video-title","ytp-webkit-ellipsis"],K:{dir:g.cJ(l.title||"")},IE:l.title},{T:"div",j:l.Ed?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
IE:l.videoDuration||void 0}]}]};y=new g.Z(R);break;case "PLAYLIST":R={T:"div",QL:["ytp-ce-element","ytp-ce-playlist"],K:{tabindex:"0","aria-label":l.Z5||"","aria-hidden":"true"},S:[{T:"div",j:"ytp-ce-element-shadow"},{T:"div",j:"ytp-ce-covering-image",K:S$(l)},{T:"div",j:"ytp-ce-covering-shadow-top"},{T:"a",j:"ytp-ce-covering-overlay",K:{href:j$(R,l.targetUrl),tabindex:"-1"},S:[{T:"div",QL:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],K:{dir:g.cJ(l.title||"")},IE:l.title},{T:"div",j:"ytp-ce-playlist-count",
S:[{T:"div",j:"ytp-ce-playlist-icon"},{T:"div",j:"ytp-ce-playlist-count-text",IE:l.playlistLength||void 0}]}]}]};y=new g.Z(R);break;case "CHANNEL":y={T:"div",QL:["ytp-ce-element","ytp-ce-channel",l.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],K:{tabindex:"0","aria-label":l.Z5||"","aria-hidden":"true"},S:[{T:"div",j:"ytp-ce-element-shadow"},{T:"div",j:"ytp-ce-expanding-overlay",S:[{T:"div",j:"ytp-ce-expanding-overlay-hider"},{T:"div",j:"ytp-ce-expanding-overlay-background"},{T:"div",j:"ytp-ce-expanding-overlay-content",
S:[{T:"div",j:"ytp-ce-expanding-overlay-body",S:[{T:"div",j:"ytp-ce-expanding-overlay-body-padding",S:[{T:"a",QL:["ytp-ce-channel-title","ytp-ce-link"],K:{href:j$(R,l.targetUrl),target:"_blank",tabindex:"-1",dir:g.cJ(l.title||"")},IE:l.title},l.subscribeButton?{T:"div",j:"ytp-ce-subscribe-container",S:[{T:"div",j:"ytp-ce-channel-subscribe"}]}:"",l.subscribersText?{T:"div",j:"ytp-ce-channel-subscribers-text",IE:l.subscribersText}:"",l.metadata?{T:"div",QL:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],IE:l.metadata}:""]}]}]}]},{T:"div",j:"ytp-ce-expanding-image",K:S$(l)}]};y=new g.Z(y);var f=g.GP(document,"div","ytp-ce-channel-subscribe",y.element)[0];if(l.subscribeButton&&l.channelId){g.AU(f,"ytp-ce-subscribe-button");if(R.player.U().X){var A=null;var K=l.sessionData.itct}else A="endscreen",K=null;A=new g.yA(l.subscribeButton.subscribeText,l.subscribeButton.subscribeCount,l.subscribeButton.unsubscribeText,l.subscribeButton.unsubscribeCount,!!l.subscribeButton.enabled,!!l.subscribeButton.classic,
l.channelId,!!l.subscribeButton.subscribed,A,K,R.player,!1);f.appendChild(A.element);R.W.push(A)}break;case "WEBSITE":R={T:"div",QL:["ytp-ce-element","ytp-ce-website"],K:{tabindex:"0","aria-label":l.Z5||"","aria-hidden":"true"},S:[{T:"div",j:"ytp-ce-element-shadow"},{T:"div",j:"ytp-ce-expanding-overlay",S:[{T:"div",j:"ytp-ce-expanding-overlay-hider"},{T:"div",j:"ytp-ce-expanding-overlay-background"},{T:"div",j:"ytp-ce-expanding-overlay-content",S:[{T:"div",j:"ytp-ce-expanding-overlay-body",S:[{T:"div",
j:"ytp-ce-expanding-overlay-body-padding",S:[{T:"div",j:"ytp-ce-website-title",K:{dir:g.cJ(l.title||"")},IE:l.title},{T:"div",j:"ytp-ce-website-metadata",IE:l.metadata},{T:"a",QL:["ytp-ce-website-goto","ytp-ce-link"],K:{href:j$(R,l.targetUrl),target:"_blank",tabindex:"-1"},IE:l.callToAction}]}]}]}]},{T:"div",j:"ytp-ce-expanding-image",K:S$(l)},{T:"div",j:"ytp-ce-expanding-icon",K:sdK(l.iconUrl)}]};y=new g.Z(R);break;case "CREATOR_MERCHANDISE":y="",l.productPrice&&(y={T:"div",j:"ytp-ce-merchandise-price-container",
S:[{T:"div",j:"ytp-ce-merchandise-price",IE:l.productPrice}]},l.additionalFeesText&&y.S.push({T:"div",j:"ytp-ce-merchandise-additional-fees",IE:l.additionalFeesText})),R={T:"div",QL:["ytp-ce-element","ytp-ce-merchandise"],K:{tabindex:"0","aria-label":l.Z5||"","aria-hidden":"true"},S:[{T:"div",j:"ytp-ce-element-shadow"},{T:"div",j:"ytp-ce-expanding-overlay",S:[{T:"div",j:"ytp-ce-expanding-overlay-hider"},{T:"div",j:"ytp-ce-expanding-overlay-background"},{T:"div",j:"ytp-ce-expanding-overlay-content",
S:[{T:"div",j:"ytp-ce-expanding-overlay-body",S:[{T:"div",j:"ytp-ce-expanding-overlay-body-padding",S:[{T:"div",j:"ytp-ce-merchandise-title",K:{dir:g.cJ(l.title||"")},IE:l.title},y,{T:"div",j:"ytp-ce-merchandise-metadata",IE:l.metadata},{T:"a",QL:["ytp-ce-merchandise-goto","ytp-ce-link"],K:{href:j$(R,l.targetUrl),target:"_blank",tabindex:"-1"},IE:l.callToAction}]}]}]}]},{T:"div",j:"ytp-ce-expanding-image",K:S$(l)},{T:"div",j:"ytp-ce-merchandise-invideo-cta-container",S:[{T:"div",j:"ytp-ce-merchandise-invideo-cta",
IE:l.callToAction||void 0}]}]},y=new g.Z(R)}l.isPlaceholder&&g.AU(y.element,"ytp-ce-placeholder");return y},S$=function(R){if(R.Cg)var l=R.Cg.thumbnails;
return sdK(l?l[l.length-1].url:null)},sdK=function(R){return R?{style:"background-image: url("+R+")"}:{}},alA=function(R,l,y){function f(H){H&&(l.listen("blur",function(){H.style.display!="none"&&R.LX&&H.focus()}),l.N(H,"focus",K),l.N(H,"blur",G))}
function A(H){R.V+=H;R.V>0?(g.AU(l.element,"ytp-ce-force-expand"),kd(R,y.id,!0)):(g.G8(l.element,"ytp-ce-force-expand"),g.G8(l.element,"ytp-ce-element-hover"),kd(R,y.id,!1))}
function K(){A(1)}
function G(){A(-1)}
l.listen("mouseenter",function(){BtZ(R,l,y)});
l.listen("mouseleave",function(){HDS(R,l,y)});
R.player.U().X||l.listen("click",function(){g.AU(l.element,"ytp-ce-element-hover")});
l.listen("click",function(H){n95(R,y,H)});
l.listen("keypress",function(H){n95(R,y,H)});
l.listen("focus",function(){BtZ(R,l,y)});
l.listen("blur",function(){HDS(R,l,y)});
l.listen("touchstart",function(){BtZ(R,l,y)});
var B=g.aA("ytp-ce-expanding-overlay-hider",l.element);B&&l.N(B,"touchstart",function(H){H.stopPropagation();g.G8(l.element,"ytp-ce-element-hover");g.G8(l.element,"ytp-ce-force-expand")});
l.listen("keydown",function(H){R.LX=H.keyCode===9&&!H.shiftKey});
f(g.aA("ytp-sb-subscribe",l.element));f(g.aA("ytp-sb-unsubscribe",l.element));l.listen("focus",K);l.listen("blur",G)},n95=function(R,l,y){if(l.targetUrl&&(!y||y.type!=="keypress"||y.keyCode===13)){for(var f=y.target;f&&!g.fg(f,"ytp-ce-element");){g.fg(f,"subscribe-label")&&m2Z(R,l);
if(g.fg(f,"ytp-ce-channel-subscribe"))return;f=f.parentElement||null}if(!f||g.fg(f,"ytp-ce-element-hover")){y.preventDefault();y.stopPropagation();if(f=R.X[l.id])HDS(R,f,l),f.element.blur();if(y.ctrlKey||y.metaKey||l.QTx==="new")m2Z(R,l),R.player.sendVideoStatsEngageEvent(17,void 0),R.player.pauseVideo(),y=g.sp(j$(R,l.targetUrl)),y=g.AM(y),g.ki(y,void 0,l.sessionData);else{var A=g.Hm(R.player.U())||R.player.getVideoData().nJ,K=function(){var G=j$(R,l.targetUrl),B=l.sessionData,H=l.watchEndpoint,n=
g.f0(G);A&&n&&(n.v||n.list)?R.player.MA(n.v,B,n.list,!1,void 0,H||void 0):g.jE(G,B)};
m2Z(R,l,function(){R.player.sendVideoStatsEngageEvent(17,K)})}}}},j$=function(R,l){R=R.player.U();
if(l){if(l.startsWith("//"))return R.protocol+":"+l;if(l.startsWith("/"))return g.LU(R)+l}else return"";return l},BtZ=function(R,l,y){g.fg(l.element,"ytp-ce-element-hover")||(y.type==="VIDEO"||y.type==="PLAYLIST"?g.AU(l.element,"ytp-ce-element-hover"):R.player.U().X?(new g.Vg(function(){g.AU(l.element,"ytp-ce-element-hover")},200)).start():g.AU(l.element,"ytp-ce-element-hover"),DM(R,y.Lu),kd(R,y.id,!0))},HDS=function(R,l,y){g.G8(l.element,"ytp-ce-element-hover");
g.G8(l.element,"ytp-ce-force-expand");kd(R,y.id,!1)},kd=function(R,l,y){R.L&&(y?R.J.show():R.J.hide());
for(var f=g.u(Object.keys(R.X)),A=f.next();!A.done;A=f.next())A=A.value,A!==l&&g.BJ(R.X[A].element,"ytp-ce-element-shadow-show",y)},DM=function(R,l,y){function f(){K||(A++,A===l.length&&(G.stop(),y&&y()))}
if(!l||l.length===0||p7(R))y&&y();else{l=o9r(R,l);var A=0,K=!1,G=new g.Vg(function(){K=!0;y&&y()},1E3,R);
G.start();for(R=0;R<l.length;R++)g.xS(l[R],f)}},m2Z=function(R,l,y){DM(R,l.clickUrls,y);
(R=g.Py())&&l.Cu&&g.l1(R,l.visualElement)},o9r=function(R,l){var y=R.player.getVideoData().clientPlaybackNonce;
R=R.player.getCurrentTime().toFixed(2);y={CPN:y,AD_CPN:y,MT:R};R=[];for(var f=0;f<l.length;f++)R.push(hAZ(l[f],y));return R},hAZ=function(R,l){return R.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(y){var f=unescape(y);
f=f.substring(1,f.length-1);return l[f]?escape(l[f]):y})},caX=function(R){return typeof R==="string"?R:""},ZM=function(R,l,y){for(var f in l)if(l[f]===R)return R;
return y},E9K=function(R,l,y,f){this.value=R;
this.target=l;this.showLinkIcon=y;this.Z=f},J8=function(R){return R.value?R.value:null},gW=function(R){if(!R)return null;
var l=g.sp(caX(R.value));l=g.AM(l);if(!l)return null;var y=ZM(R.target,WWO,"current");if(y==null)R=null;else{var f=R.show_link_icon;R=new E9K(l,y,f==="true"||f==="false"?f==="true":!0,R.pause_on_navigation!=null?R.pause_on_navigation:!0)}return R},LWU=function(R,l,y){this.type=R;
this.trigger=l;this.url=y},PcO=function(R){if(!R)return null;
var l=ZM(R.type,ODA),y=ZM(R.trigger,iDU);R=R.url;R=Array.isArray(R)&&R.length?R[0]:R;R=gW(R?R:null);return l?new LWU(l,y,R):null},u9d=function(R,l,y,f,A){this.id=R;
this.type=l;this.style=y;this.data=A;this.action=f||[]},FW8=function(R,l){return g.iA(R.action,l)},QdU=function(R,l){this.context=R;
this.Z=l},$2K=function(R){return R.customMessage?VR("div","iv-card-message",R.customMessage):""},C7=function(R,l){R="background-image: url("+R+");";
var y=[];l&&y.push(l);return{T:"div",j:"iv-card-image",K:{style:R},S:y}},eA8=function(R){if(!R.metaInfo||R.metaInfo.length===0)return"";
var l=[];R=g.u(R.metaInfo);for(var y=R.next();!y.done;y=R.next())l.push(VR("li","",y.value));return{T:"ul",j:"iv-card-meta-info",S:l}},VR=function(R,l,y){l?typeof l==="string"?l={"class":l}:Array.isArray(l)&&(l={"class":l.join(" ")}):l={};
l.dir=g.cJ(y);return{T:R,K:l,IE:y}},bDt=function(R){if(!R.customMessage)return"";
var l=["iv-card-action","iv-card-primary-link"],y={};R.bf&&(l.push("iv-card-action-icon"),y.style="background-image: url("+R.bf+");");y.dir=g.cJ(R.customMessage);var f=[{T:"span",IE:R.customMessage}];R.showLinkIcon&&(f.push("\u00a0"),f.push({T:"span",j:"iv-card-link-icon"}));return{T:"div",QL:l,K:y,S:f}},qx=function(R,l,y,f){if(f){l=g.u(l);
for(var A=l.next();!A.done;A=l.next())R.Z(A.value,f,y.id,y.sessionData,y.Ic.click,5)}},XYS=function(R,l){this.merchant=R;
this.price=l},TtK=function(R){var l;
(l=R)&&!(l=R.length>1?R.charAt(0)==="/"&&R.charAt(1)!=="/":R==="/")&&(l=R.replace(/^(https?:)?\/\//,"").split("/",1),l=!l||l.length<1||!l[0]?[]:l[0].toLowerCase().split(".").reverse(),l=l[0]==="com"&&l[1]==="youtube"||l[0]==="be"&&l[1]==="youtu");return l?R.indexOf("/redirect?")===-1:!1},d2S=function(R,l){return l?l:TtK(R)?"current":"new"},t8=function(R,l){g.p.call(this);
var y=this;this.element=R;this.context=l;this.B1=!1;this.UL=new Map;this.tU=new Map;this.context.G.addEventListener(g.Vx("annotations_module"),function(f){(f=y.UL.get(f))&&f.apply(y)});
this.context.G.addEventListener(g.Cd("annotations_module"),function(f){(f=y.tU.get(f))&&f.apply(y)})},Yd=function(R,l,y,f,A,K,G){R.context.Z.listen(l,"click",function(B){R.Mt(y,f,A,K||[],G||0,B)});
R.context.Z.listen(l,"touchstart",function(){R.B1=!1});
R.context.Z.listen(l,"touchmove",function(){R.B1=!0})},rad=function(R){var l;
return((l=g.k(R,g.wp))==null?0:l.url)?g.k(R,g.wp).url:(R=g.k(R,g.mh))&&R.videoId?(l="/watch?v="+R.videoId,R.playlistId&&(l+="&list="+R.playlistId),R.index&&(l+="&index="+R.index),R.startTimeSeconds&&(l+="&t="+R.startTimeSeconds),l):null},Mx=function(R,l,y){return{wg:(R.impressionLoggingUrlsV2s||[]).map(function(f){return f.baseUrl||""}),
click:(y.loggingUrls||[]).map(function(f){return f.baseUrl||""}),
close:(l.dismissLoggingUrlsV2s||[]).map(function(f){return f.baseUrl||""}),
ws:(l.impressionLoggingUrlsV2s||[]).map(function(f){return f.baseUrl||""}),
y7:(l.clickLoggingUrlsV2s||[]).map(function(f){return f.baseUrl||""})}},v9U=function(R,l,y){t8.call(this,l,y);
var f=this;this.G=R;this.eventId=null;this.LA=this.CX=this.sF=this.L=this.isInitialized=!1;this.cards=[];this.iQ=this.W=this.P1=this.J=this.jS=this.Z=null;this.LX=[];this.Yb=this.V=this.U9=this.sL=null;this.D=0;this.Dq=new g.Vg(function(){},y.Zq.wN?4E3:3E3);
g.U(this,this.Dq);this.uQ=new g.Vg(function(){});
g.U(this,this.uQ);this.xb=new QdU(y,function(A,K,G,B,H,n){Yd(f,A,K,G,B,H,n)});
this.B=new g.Z({T:"div",j:"iv-drawer",K:{id:"iv-drawer"},S:[{T:"div",j:"iv-drawer-header",K:{"aria-role":"heading"},S:[{T:"span",j:"iv-drawer-header-text"},{T:"button",QL:["iv-drawer-close-button","ytp-button"],K:{"aria-label":"\uce74\ub4dc \uc228\uae30\uae30",tabindex:"0"}}]},{T:"div",j:"iv-drawer-content"}]});g.U(this,this.B);this.Y=this.B.element;this.W1=new g.MF(this.B,330);g.U(this,this.W1);this.ZL=g.aA("iv-drawer-header-text",this.Y);this.X=g.aA("iv-drawer-content",this.Y);this.addCueRange(0,
y.videoData.lengthSeconds*1E3,"",function(){f.sF&&RH(f,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(f.sF=f.L)&&l9(f)});
this.v1=new g.QW(this);g.U(this,this.v1);this.G.addEventListener("videodatachange",this.f7.bind(this))},zAU=function(R,l){l=l.data;
l.autoOpenMs&&R.addCueRange(l.autoOpenMs,0x8000000000000,"",function(){RH(R,"YOUTUBE_DRAWER_AUTO_OPEN")});
l.autoCloseMs&&R.addCueRange(l.autoCloseMs,0x8000000000000,"",function(){l9(R)});
var y=l.headerText;g.Qa(R.ZL,y);R.W&&R.W.setAttribute("title",y);l.eventId&&(R.eventId=l.eventId);R.sL=g.Ll(l.trackingParams);R.V=g.Ll(l.closeTrackingParams);R.U9=g.Ll(l.iconTrackingParams)},wY8=function(R,l){var y=l.cardId?l.cardId:"cr:"+R.D,f=R.G.U().experiments.EL("enable_error_corrections_infocard_web_client");
if(!l.content&&l.teaser.simpleCardTeaserRenderer&&f){var A=l.teaser.simpleCardTeaserRenderer,K=l.icon?l.icon.infoCardIconRenderer:null;if(A.channelAvatar&&A.channelAvatar.thumbnails&&A.channelAvatar.thumbnails.length>0)var G=y0(A.channelAvatar.thumbnails,22,22).url;l={id:y,timestamp:R.D,type:"simple",teaserText:g.mF(A.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:{},sponsored:!1,Ic:{},zC:null,lE:A.trackingParams?
g.Ll(A.trackingParams):null,U9:K&&K.trackingParams?g.Ll(K.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,bf:null,title:"",customMessage:"",url:null,onClickCommand:A.onTapCommand||null,xe:G};ff(R,l)}else{var B;if((B=l.content)==null?0:B.simpleCardContentRenderer){if(!l.cueRanges.length)return;G=(A=l.content)==null?void 0:A.simpleCardContentRenderer;A=l.teaser.simpleCardTeaserRenderer;K=l.icon?l.icon.infoCardIconRenderer:null;l={id:y,timestamp:R.D,type:"simple",teaserText:g.mF(A.message),
teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:Ar(R,y,l,G),sponsored:!1,Ic:Mx(G,A,G.command),zC:G.trackingParams?g.Ll(G.trackingParams):null,lE:A.trackingParams?g.Ll(A.trackingParams):null,U9:K&&K.trackingParams?g.Ll(K.trackingParams):null,imageUrl:y0(G.image.thumbnails,290,290).url,displayDomain:G.displayDomain?g.mF(G.displayDomain):null,showLinkIcon:!!G.showLinkIcon,bf:null,title:G.title?g.mF(G.title):"",
customMessage:G.callToAction?g.mF(G.callToAction):"",url:g.k(G.command,g.wp).url?gW({pause_on_navigation:!R.context.videoData.isLivePlayback,target:"new",value:g.k(G.command,g.wp).url}):null,onClickCommand:null};ff(R,l)}else{var H;if((H=l.content)==null?0:H.collaboratorInfoCardContentRenderer){if(!l.cueRanges.length)return;G=(K=l.content)==null?void 0:K.collaboratorInfoCardContentRenderer;A=l.teaser.simpleCardTeaserRenderer;K=l.icon?l.icon.infoCardIconRenderer:null;l={id:y,timestamp:R.D,type:"collaborator",
teaserText:g.mF(A.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:Ar(R,y,l,G),sponsored:!1,Ic:Mx(G,A,G.endpoint),zC:G.trackingParams?g.Ll(G.trackingParams):null,lE:A.trackingParams?g.Ll(A.trackingParams):null,U9:K&&K.trackingParams?g.Ll(K.trackingParams):null,channelId:g.k(G.endpoint,g.pC).browseId,customMessage:G.customText?g.mF(G.customText):null,profileImageUrl:y0(G.channelAvatar.thumbnails,290,
290).url,title:G.channelName?g.mF(G.channelName):"",metaInfo:[G.subscriberCountText?g.mF(G.subscriberCountText):""],url:gW({pause_on_navigation:!R.context.videoData.isLivePlayback,target:"new",value:g.k(G.endpoint,g.pC).canonicalBaseUrl?g.k(G.endpoint,g.pC).canonicalBaseUrl:"/channel/"+g.k(G.endpoint,g.pC).browseId}),onClickCommand:null};ff(R,l)}else{var n;if((n=l.content)==null?0:n.playlistInfoCardContentRenderer){if(!l.cueRanges.length)return;var m;G=(m=l.content)==null?void 0:m.playlistInfoCardContentRenderer;
A=l.teaser.simpleCardTeaserRenderer;K=l.icon?l.icon.infoCardIconRenderer:null;l={id:y,timestamp:R.D,type:"playlist",teaserText:g.mF(A.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:Ar(R,y,l,G),sponsored:!1,Ic:Mx(G,A,G.action),zC:G.trackingParams?g.Ll(G.trackingParams):null,lE:A.trackingParams?g.Ll(A.trackingParams):null,U9:K&&K.trackingParams?g.Ll(K.trackingParams):null,y4:y0(G.playlistThumbnail.thumbnails,
258,290).url,customMessage:G.customMessage?g.mF(G.customMessage):null,playlistVideoCount:g.mF(G.playlistVideoCount),title:G.playlistTitle?g.mF(G.playlistTitle):"",metaInfo:[G.channelName?g.mF(G.channelName):"",G.videoCountText?g.mF(G.videoCountText):""],url:gW({pause_on_navigation:!R.context.videoData.isLivePlayback,target:"new",value:rad(G.action)}),onClickCommand:null};ff(R,l)}else{var h;if((h=l.content)==null?0:h.videoInfoCardContentRenderer){if(!l.cueRanges.length)return;var c;G=(c=l.content)==
null?void 0:c.videoInfoCardContentRenderer;A=l.teaser.simpleCardTeaserRenderer;K=l.icon?l.icon.infoCardIconRenderer:null;l={id:y,timestamp:R.D,type:"video",teaserText:g.mF(A.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:Ar(R,y,l,G),sponsored:!1,Ic:Mx(G,A,G.action),zC:G.trackingParams?g.Ll(G.trackingParams):null,lE:A.trackingParams?g.Ll(A.trackingParams):null,U9:K&&K.trackingParams?g.Ll(K.trackingParams):
null,y4:y0(G.videoThumbnail.thumbnails,258,290).url,videoDuration:G.lengthString?g.mF(G.lengthString):null,customMessage:G.customMessage?g.mF(G.customMessage):null,title:G.videoTitle?g.mF(G.videoTitle):"",metaInfo:[G.channelName?g.mF(G.channelName):"",G.viewCountText?g.mF(G.viewCountText):""],isLiveNow:!!G.badge,url:gW({pause_on_navigation:!R.context.videoData.isLivePlayback,target:"new",value:rad(G.action)}),onClickCommand:null};ff(R,l)}}}}}R.D++},y0=function(R,l,y){for(var f=-1,A=-1,K=0;K<R.length;K++){if(R[K].height===
l||R[K].width===y)return R[K];
((R[K].height||0)<l||(R[K].width||0)<y)&&(f<0||(R[f].height||0)<(R[K].height||0)||(R[f].width||0)<(R[K].width||0))?f=K:((R[K].height||0)>=l||(R[K].width||0)>=y)&&(A<0||(R[A].height||0)>(R[K].height||0)||(R[A].width||0)>(R[K].width||0))&&(A=K)}return R[A>=0?A:f]},Ar=function(R,l,y,f){return{feature:y.feature?y.feature:"cards",
src_vid:R.context.videoData.videoId,annotation_id:l,ei:R.context.videoData.eventId||"",itct:f.trackingParams||""}},Ilr=function(R,l){if(l=x25(R,l))l===R.Z&&(R.Z=null),R.G.removeCueRange(l.gx.id),g.Ot(l.R0),g.bA(R.cards,l),R.Sz(),Kf(R)},RH=function(R,l,y){if(!R.L){R.W1.show();
R.jS=new g.Vg(function(){g.AU(R.context.G.getRootNode(),g.nA.IV_DRAWER_OPEN)},0);
R.jS.start();R.v1.N(R.X,"mousewheel",function(G){R.Dq.start();G.preventDefault();G=G||window.event;var B=0;G.type=="MozMousePixelScroll"?B=0==(G.axis==G.HORIZONTAL_AXIS)?G.detail:0:window.opera?B=G.detail:B=G.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?G.wheelDeltaY/-30:G.wheelDeltaY/-1.2:G.wheelDelta/-1.6:G.wheelDeltaY/-3;if(G=B)R.X.scrollTop+=G});
R.L=!0;var f=g.Py();f&&R.sL&&R.V&&g.MJ(f,[R.sL,R.V]);l={TRIGGER_TYPE:l};for(var A=g.u(R.cards),K=A.next();!K.done;K=A.next())K=K.value,K.SV||(K.SV=!0,NtD(R.context.logger,K.gx.Ic.wg,l)),f&&g.MJ(f,[K.gx.zC]);Ti(R.G);y&&(R.J=new g.Vg(function(){R.P1=R.W;R.iQ.focus()},330),R.J.start())}},l9=function(R){R.L&&(R.W1.hide(),g.Xr(R.v1),g.G8(R.context.G.getRootNode(),g.nA.IV_DRAWER_OPEN),R.L=!1,Ti(R.G),R.J&&R.J.stop(),R.J=new g.Vg(function(){R.P1&&(R.P1.focus(),R.P1=null)},330),R.J.start())},pY8=function(R){g.Kg(R.al(),
[g.nA.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.kT(R.G,R.Y,5);R.vx();R.W=g.aA("ytp-cards-button",R.G.getRootNode());R.iQ=g.aA("iv-drawer-close-button",R.Y);R.isInitialized=!0},U2Z=function(R){R.LX.push(g.Rn("iv-teaser-shown",R.Sf,R));
R.LX.push(g.Rn("iv-teaser-hidden",R.le,R));R.LX.push(g.Rn("iv-teaser-clicked",R.u0,R));R.LA=!0},SMU=function(R,l){var y;
return l.onClickCommand&&((y=g.k(l.onClickCommand,g.LHO))==null?void 0:y.targetId)==="engagement-panel-error-corrections"?(R.Yb=l,!0):!1},jdA=function(R,l){R.Yb=l;
var y=R.G.getVideoData();if(!y)return!1;y=g.ju(y);if(y==null?0:y.markersMap)for(var f,A=0;((f=y)==null?void 0:f.markersMap.length)>A;A++){var K=void 0,G=(K=y)==null?void 0:K.markersMap[A];if(G.key==="ERROR_CORRECTION_MARKERS"&&(K=void 0,(G=(K=G.value)==null?void 0:K.markers)&&G.length>0))return f=void 0,l.startMs=((f=g.k(G[0],g.ArT))==null?void 0:f.timeRangeStartMillis)||0,R.Yb=null,!0}return!1},ff=function(R,l){if(!SMU(R,l)||jdA(R,l)){var y=kmr(R,l);
if(y){var f={gx:l,R0:y.element,SV:!1};if(l.onClickCommand)R.G.C("web_infocards_teaser_show_logging_fix")&&(R.LA||U2Z(R),Ilr(R,l.id),y=R.findLastIndex(f),g.Sd(R.cards,y,0,f));else{R.isInitialized||pY8(R);Ilr(R,l.id);var A=R.findLastIndex(f);g.Sd(R.cards,A,0,f);y.JU(R.X,A);R.Sz()}l.autoOpen?R.addCueRange(l.startMs,0x8000000000000,l.id,function(){R.L||(R.Z=f,Kf(R),D28(R,f),RH(R,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(y=R.context.G.getCurrentTime()*1E3,y<5E3&&y>l.startMs&&ZDD(R,f),R.addCueRange(l.startMs,
l.startMs+1,l.id,function(){ZDD(R,f)}),Kf(R))}}},kmr=function(R,l){switch(l.type){case "simple":R=R.xb;
var y=l.displayDomain?{T:"div",j:"iv-card-image-text",IE:l.displayDomain}:void 0;var f=bDt(l);y={T:"div",QL:["iv-card"],S:[{T:"a",j:"iv-click-target",K:{href:l.url?J8(l.url)||"":""},S:[C7(l.imageUrl,y),{T:"div",j:"iv-card-content",S:[VR("h2",void 0,l.title),f]}]}]};y=new g.Z(y);qx(R,g.KS("iv-click-target",y.element),l,l.url);l=y;break;case "collaborator":R=R.xb;y={T:"div",QL:["iv-card","iv-card-channel"],S:[{T:"a",QL:["iv-click-target"],K:{href:J8(l.url)||"","data-ytid":l.channelId},S:[C7(l.profileImageUrl),
{T:"div",j:"iv-card-content",S:[$2K(l),{T:"h2",j:"iv-card-primary-link",IE:l.title},eA8(l)]}]}]};y=new g.Z(y);qx(R,g.KS("iv-click-target",y.element),l,l.url);l=y;break;case "playlist":R=R.xb;y={T:"div",QL:["iv-card","iv-card-playlist"],S:[{T:"a",j:"iv-click-target",K:{href:J8(l.url)||""},S:[C7(l.y4,{T:"div",j:"iv-card-image-overlay",S:[{T:"span",j:"iv-card-playlist-video-count",IE:l.playlistVideoCount}]}),{T:"div",j:"iv-card-content",S:[$2K(l),VR("h2","iv-card-primary-link",l.title),eA8(l)]}]}]};
y=new g.Z(y);qx(R,g.KS("iv-click-target",y.element),l,l.url);l=y;break;case "productListing":R=R.xb;var A=l.offers.length!=0;y=["iv-card"];f="";var K=bDt(l);A&&(y.push("iv-card-product-listing"),f="iv-card-primary-link",K=l.offers[0],A=[],K.price&&A.push({T:"div",j:"iv-card-offer-price",IE:K.price}),K.merchant&&A.push({T:"div",j:"iv-card-offer-merchant",IE:K.merchant}),K={T:"div",S:A});A=l.url?J8(l.url)||"":"";y={T:"div",QL:y,K:{tabindex:"0"},S:[{T:"a",QL:["iv-card-image","iv-click-target"],K:{style:"background-image: url("+
l.imageUrl+");",href:A,"aria-hidden":"true",tabindex:"-1"}},{T:"div",j:"iv-card-content",S:[l.sponsored?{T:"div",j:"iv-card-sponsored",S:["\uc2a4\ud3f0\uc11c",{T:"div",j:"iv-ad-info-container",S:[{T:"div",j:"iv-ad-info",IE:"{{adInfo}}"},{T:"div",j:"iv-ad-info-icon-container",S:[{T:"div",j:"iv-ad-info-icon"},{T:"div",j:"iv-ad-info-callout"}]}]}]}:"",{T:"a",j:"iv-click-target",K:{href:A},S:[VR("h2",f,l.title),K]}]}]};y=new g.Z(y);f=g.ho("span");g.Qa(f,"\ub3d9\uc601\uc0c1\uacfc \uad00\ub828\uc774 \uc788\ub294 \uac83\uc73c\ub85c \ubcf4\uc5ec \uc81c\ud488\uc774 \ud45c\uc2dc\ub418\uc5c8\uc2b5\ub2c8\ub2e4. Google\uc5d0\uc11c \ud310\ub9e4\uc790\ub85c\ubd80\ud130 \ubcf4\uc0c1\uc744 \ubc1b\uc744 \uc218\ub3c4 \uc788\uc2b5\ub2c8\ub2e4.");
y.Oj(f,"adInfo");qx(R,g.KS("iv-click-target",y.element),l,l.url);l=y;break;case "video":R=R.xb;f=l.videoDuration?{T:"span",j:"iv-card-video-duration",IE:l.videoDuration}:void 0;K=l.isLiveNow?{T:"span",QL:["yt-badge","yt-badge-live"],IE:"\uc2e4\uc2dc\uac04"}:null;A={T:"div",QL:["iv-card","iv-card-video"],S:[{T:"a",j:"iv-click-target",K:{href:((y=l.url)==null?void 0:J8(y))||""},S:[C7(l.y4,f),{T:"div",j:"iv-card-content",S:[$2K(l),VR("h2","iv-card-primary-link",l.title),eA8(l),K]}]}]};y=new g.Z(A);qx(R,
g.KS("iv-click-target",y.element),l,l.url);l=y;break;default:return null}return l},JaK=function(R){if(R.Z)return R.Z.gx.type==="productListing";
if(R.G.C("enable_wn_infocards")){var l;return!((l=R.cards)==null||!l.length)&&g.OJ(R.cards,function(y){return y.gx.type==="productListing"})}return g.OJ(R.cards,function(y){return y.gx.type==="productListing"})},Kf=function(R){g.BJ(R.G.getRootNode(),"ytp-cards-shopping-active",JaK(R))},ZDD=function(R,l){if(!g.fg(R.G.getRootNode(),"ytp-cards-teaser-shown")){if(R.Z!==l){var y=g.Py(),f=R.Z?R.Z.gx.U9:R.U9;
y&&f&&g.RN(y,[f]);R.Z=l;Kf(R)}(y=R.isInitialized&&R.al().style.display=="none")||(y=R.context.G.getPlayerState(),f=y===0&&R.context.G.getCurrentTime()===0,y=!(y===1||y===3||f));if(!y&&l.gx.teaserDurationMs){var A;y={teaserText:l.gx.teaserText,durationMs:l.gx.teaserDurationMs,onClickCommand:l.gx.onClickCommand,xe:(A=l.gx.xe)!=null?A:null};R.G.G7(!0,y)}R.uQ.isActive()||((!R.L||!R.Dq.isActive()&&R.CX)&&D28(R,l),R.uQ.start(910+l.gx.teaserDurationMs))}},D28=function(R,l){R.B.m$?(l=new wW([0,
R.X.scrollTop],[0,l.R0.offsetTop],600,YJK),R.context.L.listen(l,"animate",function(y){R.X.scrollTop=y.y}),R.context.L.listen(l,"finish",function(y){R.X.scrollTop=y.y}),l.play()):(R.B.UF(!0),R.X.scrollTop=l.R0.offsetTop,R.B.UF(!1))},G7=function(R){return R.Z&&R.Z.gx?R.Z.gx:R.cards[0]&&R.cards[0].gx?R.cards[0].gx:null},x25=function(R,l){return g.iA(R.cards,function(y){return y.gx.id===l})},aH=function(R,l,y){t8.call(this,R,l);
this.annotation=y;this.isActive=!1},g9K=function(R){var l=R.annotation.data;
"start_ms"in l&&"end_ms"in l&&R.addCueRange(Number(l.start_ms),Number(l.end_ms),R.annotation.id,function(){R.show()},function(){R.hide()})},sc=function(R,l,y){aH.call(this,R,l,y);
this.X=null;this.V=!1;this.L=null;this.Y=!1;this.Z=this.D=this.J=null},V4Z=function(R,l){var y=y===void 0?0:y;
var f=koO(l).width;g.qh(l,f);y=new qJU(l,[f,l.offsetTop],[f-f-y,l.offsetTop],200,tSU);g.U(R,y);R.context.L.listen(y,"begin",function(){g.yT(l,!0)});
y.play()},t4D=function(R,l){if(l.channel_name){var y=R.createElement({T:"div",
QL:["iv-branding-context-name"],IE:l.channel_name}),f=R.createElement({T:"div",QL:["iv-branding-context-subscribe"]}),A=l.standalone_subscribe_button_data;A&&(R.Z=new g.yA(A.subscribeText,A.subscribeCount,A.unsubscribeText,A.unsubscribeCount,!!A.enabled,!!A.classic,l.channel_id,!!A.subscribed,A.feature,l.session_data.itct,R.context.G,!1),R.Z.JU(f));var K=R.createElement({T:"div",QL:["iv-branding-context-subscribe-caret"]}),G=R.createElement({T:"div",QL:["branding-context-container-inner"]});G.appendChild(K);
G.appendChild(y);G.appendChild(f);g.yT(G,!1);var B=R.createElement({T:"div",QL:["branding-context-container-outer"]});B.appendChild(G);g.Df(B,"right",l.image_width+"px");g.Et(R.al(),B);R.L=new g.Vg(function(){CcS(R,G,B)},500);
g.U(R,R.L);R.context.Z.listen(R.al(),"mouseover",function(){qMD(R,G,B,K,l.image_height)});
R.context.Z.listen(R.al(),"mouseout",function(){R.L.start()})}},qMD=function(R,l,y,f,A){R.L.stop();
if(!R.Y){var K=g.l4(l);R.Z||(l.style.width=g.CS(K.width,!0),y.style.width=g.CS(K.width,!0));g.Df(f,"top",K.height-Math.max(Math.min(K.height,A)/2+10,20)+"px");g.Df(f,"right","1px");R.Y=!0;g.yT(l,!0);R.J=new g.Vg(function(){g.AU(this.al(),"iv-branding-active")},0,R);
R.J.start()}},CcS=function(R,l,y){g.G8(R.al(),"iv-branding-active");
R.D=new g.Vg(function(){g.yT(l,!1);R.Z||(y.style.width=g.CS(0,!0))},250);
R.D.start();R.Y=!1},YMA=function(R,l,y,f,A,K,G){this.Z=R;
this.L=l;this.Zq=y;this.videoData=f;this.logger=A;this.G=K;this.X=G},M4U=function(R,l,y){aH.call(this,R,l,y);
var f=this;this.W=this.isCollapsed=this.B=!1;this.D=5E3;this.X=this.L=this.Z=this.Y=null;this.V=this.createElement({T:"div",QL:["iv-promo-contents"]});this.J=new g.Vg(function(){f.Z.setAttribute("aria-hidden","true");g.yT(f.L,!1);g.yT(f.X,!0)},700,this);
g.U(this,this.J)},laU=function(R){var l=R.annotation.data;
if(R.annotation.style==="cta")var y=6;else if(R.annotation.style==="video"||R.annotation.style==="playlist")y=7;R.D=l.collapsedelay_ms||R.D;var f=["iv-promo","iv-promo-inactive"];R.al().setAttribute("aria-hidden","true");R.al().setAttribute("aria-label","\ud504\ub85c\ubaa8\uc158");R.al().tabIndex=0;var A=R.annotation.Jk(),K=l.image_url;if(K){var G=R.createElement({T:"div",QL:["iv-promo-img","iv-click-target"]});K=R.createElement({T:"img",K:{src:K,"aria-hidden":"true"}});G.appendChild(K);l.video_duration&&
!l.is_live?(K=R.createElement({T:"span",j:"iv-promo-video-duration",IE:l.video_duration}),G.appendChild(K)):l.playlist_length&&(K=R.createElement({T:"span",j:"iv-promo-playlist-length",IE:l.playlist_length.toString()}),G.appendChild(K));A&&Yd(R,G,A,R.annotation.id,l.session_data,void 0,y)}A?(K=R.createElement({T:"a",j:"iv-promo-txt"}),g.H4(K,J8(A)),R.Z=K):R.Z=R.createElement({T:"div",j:"iv-promo-txt"});switch(R.annotation.style){case "cta":case "website":var B=R.createElement({T:"p",S:[{T:"strong",
IE:l.text_line_1}]});var H=R.createElement({T:"p",S:[{T:"span",j:"iv-promo-link",IE:l.text_line_2}]});if(K=l.text_line_3){f.push("iv-promo-website-card-cta-redesign");var n=R.createElement({T:"button",QL:["iv-promo-round-expand-icon","ytp-button"]});K=R.createElement({T:"button",QL:["iv-button","iv-promo-button"],S:[{T:"span",j:"iv-button-content",IE:K}]});var m=R.createElement({T:"div",j:"iv-promo-button-container"});m.appendChild(K);A&&Yd(R,R.al(),A,R.annotation.id,l.session_data,void 0,y)}g.AU(R.Z,
"iv-click-target");A&&Yd(R,R.Z,A,R.annotation.id,l.session_data,void 0,y);break;case "playlist":case "video":B=R.createElement({T:"p",S:[{T:"span",IE:l.text_line_1}]}),H=R.createElement({T:"p",S:[{T:"strong",IE:l.text_line_2}]}),l.is_live&&(B=H,H=R.createElement({T:"span",QL:["yt-badge","iv-promo-badge-live"],IE:"\uc2e4\uc2dc\uac04"})),g.AU(R.Z,"iv-click-target"),A&&Yd(R,R.Z,A,R.annotation.id,l.session_data,void 0,y),f.push("iv-promo-video")}B&&R.Z.appendChild(B);H&&R.Z.appendChild(H);R.V.appendChild(R.Z);
m&&R.V.appendChild(m);y=R.createElement({T:"div",j:"iv-promo-actions"});R.X=R.createElement({T:"button",QL:["iv-promo-expand","ytp-button"]});R.X.title="\ud655\uc7a5";R.context.Z.listen(R.X,"click",function(h){R3K(R,5E3,h)});
y.appendChild(R.X);g.yT(R.X,!1);R.context.Z.listen(R.al(),"mouseover",R.A0,R);R.context.Z.listen(R.al(),"mouseout",R.NR,R);R.context.Z.listen(R.al(),"touchend",function(h){R3K(R,5E3,h)});
R.L=R.createElement({T:"button",QL:["iv-promo-close","ytp-button"]});R.L.title="\ub2eb\uae30";R.context.Z.listen(R.L,"click",R.annotation.style==="cta"&&l.text_line_3?R.fp:R.vD,R);y.appendChild(R.L);g.Kg(R.al(),f);G&&(g.Et(R.al(),G),n&&G.appendChild(n));g.Et(R.al(),R.V);g.Et(R.al(),y)},R3K=function(R,l,y){y.stopPropagation();
yb5(R);faK(R,l);R.Z.focus()},AbU=function(R){R.isCollapsed||R.W||R.Y||(g.AU(R.al(),"iv-promo-collapsed"),R.isCollapsed=!0,R.J.start())},yb5=function(R){R.J.stop();
R.isCollapsed&&(g.ac(R.al(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),R.isCollapsed=!1,R.Z&&R.Z.removeAttribute("aria-hidden"),g.yT(R.X,!1),g.yT(R.L,!0))},faK=function(R,l){R.Y||(R.Y=g.N_(function(){KJA(this);
AbU(this)},l,R))},KJA=function(R){R.Y&&(g.Mo.clearTimeout(R.Y),R.Y=null)},G_O=function(R){this.G=R},NtD=function(R,l,y){l&&(y?Bc(R,l.map(function(f){return g.TS(f,y)})):Bc(R,l))},Bc=function(R,l,y,f){var A=1,K=void 0,G=-1;
if(y){var B=!1;K=function(){A--;A||B||(clearTimeout(G),B=!0,y())};
G=setTimeout(function(){B=!0;y()},1E3)}l=g.u(l||[]);
for(var H=l.next();!H.done;H=l.next())H=H.value,A++,g.xS(H,K);f&&(A++,f!==0&&R.G.sendVideoStatsEngageEvent(f,K))},aaA=function(R){g.Fc.call(this,R);
var l=this;this.LX=this.W=!1;this.loadNumber=0;this.D={};this.logger=new G_O(this.player);this.Y=new g.QW(this);this.J=this.V=null;this.events=new g.QW(this);this.Ls=this.B=this.Z=null;this.Yb=[];g.U(this,this.Y);this.Y.N(this.player,"onVideoAreaChange",function(){l.publish("onVideoAreaChange")});
this.Y.N(this.player,"onHideControls",function(){l.publish("onHideControls")});
this.Y.N(this.player,"onShowControls",function(){l.publish("onShowControls")});
this.Y.N(this.player,"resize",function(f){l.publish("resize",f)});
this.Y.N(this.player,"presentingplayerstatechange",function(f){l.publish("presentingplayerstatechange",f)});
this.subscribe("presentingplayerstatechange",this.l0,this);this.subscribe("resize",this.hS,this);this.player.U().CX.subscribe("vast_info_card_add",this.aX,this);g.U(this,this.events);this.xb=this.createElement({T:"div",j:"video-custom-annotations"});this.X=new g.Z({T:"div",QL:["ytp-player-content","ytp-iv-player-content"]});g.U(this,this.X);g.kT(this.player,this.X.element,4);this.X.hide();this.L=new g.Z({T:"div",QL:["ytp-iv-video-content"]});g.U(this,this.L);R=this.createElement({T:"div",j:"video-annotations"});
R.appendChild(this.xb);this.L.element.appendChild(R);this.S9()&&this.load();var y=this.createElement({T:"style"});(g.Ao("HEAD")[0]||document.body).appendChild(y);this.addOnDisposeCallback(function(){g.Ot(y)});
if(R=y.sheet)R.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),R.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),R.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),R.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),R.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),R.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),R.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),R.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),R.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),R.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},sfU=function(R){R=R.createElement({T:"div",
QL:["annotation","annotation-type-custom"]});g.yT(R,!1);return R},Bk5=function(R,l){l=!l.isCued()&&!g.V(l,1024);
R.X.UF(l);R.L.UF(l)},HYA=function(R,l,y){R.W=!0;
R.J=g.Qt(l,y)},nGU=function(R,l){for(var y={},f=g.u(l.attributes),A=f.next();!A.done;A=f.next())A=A.value,y[A.name]=A.nodeValue;
for(f=0;f<l.childNodes.length;f++)if(A=l.childNodes[f],g.GK(A)&&A.nodeType==1){if(y[A.tagName])var K=y[A.tagName];else if(A.tagName==="data"){A.childNodes.length>0&&(K=A.childNodes[0].nodeValue,y[A.tagName]=typeof K==="string"?K.trim():K);continue}else K=[],y[A.tagName]=K;A&&A.tagName==="TEXT"?A.childNodes.length===1&&A.childNodes[0].nodeType===3?K.push(A.childNodes[0].nodeValue):K.push(""):A&&K.push(nGU(R,A))}return y},cb8=function(R){var l=R.player.getVideoData();
if(l.v1){var y=R.player.U().CX.get(l.videoId);if(y){var f={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(A,K,G){A=R.loadNumber;K=l.videoId;R.loaded&&R.loadNumber===A&&R.player.getVideoData().videoId===K&&(G=g.ow(G)&&G.responseXML?G.responseXML:null)&&mSZ(R,G)}};
g.Rq()&&(f.onFinish=oG5(R,f.onFinish));f.postParams={ic_only:"1"};h3r(f,y);R.W=!0;g.Qt(l.v1,f)}}},h3r=function(R,l){R.method="POST";
R.postParams=R.postParams||{};l.rl&&(R.postParams.ic_coll=l.rl);l.Qt&&(R.postParams.ic_xml=l.Qt);l.JA&&(R.postParams.ic_track=l.JA)},EGt=function(R){var l=new g.Z({T:"div"});
g.yT(l.element,!1);var y=new v9U(R.player,l.element,Hc(R));g.U(y,l);l.JU(R.X.element);y.Bu();return y},LJD=function(R,l){var y,f;
if(l=(y=l.getWatchNextResponse())==null?void 0:(f=y.cards)==null?void 0:f.cardCollectionRenderer)R.LX=!0,WJU(R,l),l.headerText&&R.Ls&&(y=g.mF(l.headerText),R.Ls.setAttribute("title",y))},Hc=function(R){if(!R.B){var l=new MSD(R);
g.U(R,l);var y=new g.W6(R);g.U(R,y);R.B=new YMA(l,y,R.player.U(),R.player.getVideoData(),R.logger,R.player,R.pw)}return R.B},mSZ=function(R,l){var y=!1,f=l.getElementsByTagName("annotations");
if(f&&!(f.length<1)&&(f=f[0].getAttribute("itct"))){var A=g.Py();if(A){var K=g.ir();K&&g.qM(g.jh)(void 0,A,K,[g.Ll(f)])}}l=l.getElementsByTagName("annotation");for(f=0;f<l.length;f++){K=nGU(R,l[f]);A=null;try{if(K){var G=K.id,B=/.+/;var H=typeof G==="string"&&B!=null&&G!=null&&G.match(B)?G:"";var n=ZM(K.type,OYr),m=ZM(K.style,iY8),h=caX(K.data),c=h.length!==0?JSON.parse(h):{};var E=K.action;K=PcO;if(E==null)var W=null;else if(g.KX(E)){B=[];for(var Q=g.u(E),e=Q.next();!e.done;e=Q.next()){var r=K(e.value);
r&&B.push(r)}W=B}else{var d=K(E);W=d?[d]:[]}A=H&&n?new u9d(H,n,m,W,c):null}else A=null}catch(Ac){}if(A)if(A.type==="branding"||A.type==="promotion"){K=R;B=A;var z=sfU(K),N=null;switch(B.type){case "branding":if(K.player.U().Ms)break;K.X.element.appendChild(z);N=new sc(z,Hc(K),B);break;case "promotion":g.kT(K.player,z,4),N=new M4U(z,Hc(K),B)}N&&N.Bu();if(K=N)g.U(R,K),R.D[A.id]=K}else if(A.type==="card"||A.type==="drawer"){R.Z||(R.Z=EGt(R),g.U(R,R.Z));if(A.type==="card"){z=R.Z;var D=(y=A)&&y.data&&
y.data.card_type;A=y.data;if(D)switch(K=A.tracking||{},K={wg:K.impression,click:K.click,close:K.close,ws:K.teaser_impression,y7:K.teaser_click},B=A.tracking_params||{},N=null,D){case "collaborator":y={id:y.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Ic:K,zC:B.card?g.Ll(B.card):null,lE:B.teaser?g.Ll(B.teaser):null,U9:B.icon?g.Ll(B.icon):
null,channelId:A.channel_id,customMessage:A.custom_message?A.custom_message:null,profileImageUrl:A.image_url,title:A.title,metaInfo:A.meta_info,url:gW({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null};ff(z,y);break;case "playlist":y={id:y.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Ic:K,
zC:B.card?g.Ll(B.card):null,lE:B.teaser?g.Ll(B.teaser):null,U9:B.icon?g.Ll(B.icon):null,y4:A.image_url,playlistVideoCount:A.playlist_video_count,customMessage:A.custom_message?A.custom_message:null,title:A.title,metaInfo:A.meta_info,url:gW({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null};ff(z,y);break;case "productListing":A.signin_url&&(N=gW({target:"current",value:A.signin_url}));D=[];for(var t=A.offers||[],C=0;C<t.length;C++)D.push(new XYS(g.rF(t[C].merchant),
g.rF(t[C].price)));y={id:y.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Ic:K,zC:B.card?g.Ll(B.card):null,lE:B.teaser?g.Ll(B.teaser):null,U9:B.icon?g.Ll(B.icon):null,imageUrl:A.image_url,displayDomain:A.display_domain?A.display_domain:null,showLinkIcon:!!A.show_link_icon,bf:A.button_icon_url?A.button_icon_url:null,title:A.title,customMessage:A.custom_message?
A.custom_message:null,url:gW({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),MiU:N,BuL:A.signin_title?A.signin_title:void 0,H87:A.signin_message?A.signin_message:void 0,offers:D,onClickCommand:null};ff(z,y);break;case "simple":y={id:y.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Ic:K,zC:B.card?g.Ll(B.card):
null,lE:B.teaser?g.Ll(B.teaser):null,U9:B.icon?g.Ll(B.icon):null,imageUrl:A.image_url,displayDomain:A.display_domain?A.display_domain:null,showLinkIcon:!!A.show_link_icon,bf:A.button_icon_url?A.button_icon_url:null,title:A.title,customMessage:A.custom_message?A.custom_message:null,url:gW({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null};ff(z,y);break;case "video":y={id:y.id,timestamp:A.timestamp||0,type:A.card_type,teaserText:A.teaser_text,teaserDurationMs:A.teaser_duration_ms,
startMs:A.start_ms,autoOpen:A.auto_open||!1,sessionData:A.session_data||{},sponsored:A.sponsored||!1,Ic:K,zC:B.card?g.Ll(B.card):null,lE:B.teaser?g.Ll(B.teaser):null,U9:B.icon?g.Ll(B.icon):null,y4:A.image_url,videoDuration:A.video_duration||null,customMessage:A.custom_message?A.custom_message:null,title:A.title,metaInfo:A.meta_info,isLiveNow:!!A.is_live_now,url:gW({pause_on_navigation:A.pause_on_navigation,target:A.target||"new",value:A.url}),onClickCommand:null},ff(z,y)}}else zAU(R.Z,A);y=!0}}y&&
(Ti(R.player),R.hS())},WJU=function(R,l){var y=!1;
R.Z||(R.Z=EGt(R),g.U(R,R.Z));for(var f=g.u(l.cards||[]),A=f.next();!A.done;A=f.next())A=A.value,A.cardRenderer&&(wY8(R.Z,A.cardRenderer),y=!0);if(y){var K;(K=R.player.getVideoData())!=null&&g.Jt(K)||(y=R.Z,f=l.headerText?g.mF(l.headerText):"",g.Qa(y.ZL,f),y.W&&y.W.setAttribute("title",f),y.context.videoData.eventId&&(y.eventId=y.context.videoData.eventId),y.sL=l.trackingParams?g.Ll(l.trackingParams):null,y.V=l.closeButton.infoCardIconRenderer.trackingParams?g.Ll(l.closeButton.infoCardIconRenderer.trackingParams):
null,y.U9=l.icon.infoCardIconRenderer.trackingParams?g.Ll(l.icon.infoCardIconRenderer.trackingParams):null,R.hS());Ti(R.player)}},PTA=function(R,l,y,f,A){if(!R.player.U().Ms){var K=[];
l.navigationEndpoint&&g.k(l.navigationEndpoint,g.pC)&&g.k(l.navigationEndpoint,g.pC).browseId&&K.push(new LWU("openUrl","click",new E9K("/channel/"+g.k(l.navigationEndpoint,g.pC).browseId,"new",!0,!0)));var G=l.watermark.thumbnails[0];f={channel_name:l.channelName,end_ms:l.endTimeMs,image_height:G.height,image_type:1,image_url:G.url,image_width:G.width,is_mobile:!1,session_data:{annotation_id:y,ei:A,feature:"iv",itct:l.trackingParams,src_vid:f},start_ms:l.startTimeMs};if(l.subscribeButton&&g.k(l.subscribeButton,
g.UU)){f.channel_id=g.k(l.subscribeButton,g.UU).channelId;var B;l=g.k(l.subscribeButton,g.UU);G=A=null;l.subscribed?(l.subscriberCountWithUnsubscribeText&&(A=g.mF(l.subscriberCountWithUnsubscribeText)),l.subscriberCountText&&(G=g.mF(l.subscriberCountText))):(l.subscriberCountText&&(A=g.mF(l.subscriberCountText)),l.subscriberCountWithSubscribeText&&(G=g.mF(l.subscriberCountWithSubscribeText)));var H,n=((H=g.k((B=l.signInEndpoint)==null?void 0:B.commandMetadata,g.Qn))==null?void 0:H.url)||"";B={subscribeText:g.mF(l.unsubscribedButtonText),
subscribeCount:A||"",unsubscribeText:g.mF(l.subscribedButtonText),unsubscribeCount:G||"",enabled:l.enabled||!1,classic:!1,subscribed:l.subscribed||!1,feature:"iv",signInUrl:n};f.standalone_subscribe_button_data=B}K=new u9d(y,"branding","branding",K,f);B=sfU(R);R.X.element.appendChild(B);K=new sc(B,Hc(R),K);K.Bu();g.U(K,K);R.D[y]=K}},oG5=function(R,l){return function(){var y=g.SJ.apply(0,arguments);
R.Fx()||R.Yb.push(g.pz.Oi(function(){l.apply(null,g.ci(y))}))}},u7X=function(R){return R==="annotation-editor"||R==="live-dashboard"};
g.wn.prototype.G7=g.Kk(39,function(R,l){var y=g.xw(this.Il());y&&y.G7(R,l)});
var rW={},v7=null;g.hK(wW,g.HJ);g.L=wW.prototype;g.L.getDuration=function(){return this.duration};
g.L.play=function(R){if(R||this.Z==0)this.progress=0,this.coords=this.X;else if(this.isPlaying())return!1;zi(this);this.startTime=R=g.mU();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Y=this.startTime;this.progress||this.FT();this.gL("play");this.isPaused()&&this.gL("resume");this.Z=1;var l=g.s5(this);l in rW||(rW[l]=this);JWZ();gQ5(this,R);return!0};
g.L.stop=function(R){zi(this);this.Z=0;R&&(this.progress=1);VSS(this,this.progress);this.onStop();this.TA()};
g.L.pause=function(){this.isPlaying()&&(zi(this),this.Z=-1,this.gL("pause"))};
g.L.G4=function(){this.Z==0||this.stop(!1);this.gL("destroy");wW.lO.G4.call(this)};
g.L.destroy=function(){this.dispose()};
g.L.Bb=function(){this.gL("animate")};
g.L.gL=function(R){this.dispatchEvent(new C45(R,this))};
g.hK(C45,g.gJ);g.hK(xd,wW);xd.prototype.L=function(){};
xd.prototype.Bb=function(){this.L();xd.lO.Bb.call(this)};
xd.prototype.TA=function(){this.L();xd.lO.TA.call(this)};
xd.prototype.FT=function(){this.L();xd.lO.FT.call(this)};
g.hK(qJU,xd);qJU.prototype.L=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.O(MSD,g.p);g.L=MSD.prototype;g.L.listen=function(R,l,y,f){y=(0,g.B8)(y,f||this.X);R=g.PW(R,l,y);this.Z.push(R);return R};
g.L.IN=function(R,l,y,f){y=(0,g.B8)(y,f||this.X);R=DdU(R,l,y);this.Z.push(R);return R};
g.L.p_=function(R){g.uJ(R);g.bA(this.Z,R)};
g.L.removeAll=function(){g.uJ(this.Z);this.Z.length=0};
g.L.G4=function(){this.removeAll();g.p.prototype.G4.call(this)};g.O(yar,g.Fc);g.L=yar.prototype;g.L.load=function(){g.Fc.prototype.load.call(this);if(!p7(this)){var R=g.Tmq(this.player.getVideoData());R?(R=llO(R,flr(this)),Uk(this,R,!1)):AaU(this)}};
g.L.unload=function(){Uk(this,null);this.Y&&(this.Y.abort(),this.Y=null);g.Fc.prototype.unload.call(this)};
g.L.MD=function(R,l){return p7(this)?R==="loadCustomEndscreenRenderer"?(R=llO(l,"new"),Uk(this,R),!0):null:null};
g.L.getOptions=function(){return p7(this)?["loadCustomEndscreenRenderer"]:[]};
g.L.ub=function(){if(this.endscreen&&this.endscreen.elements){var R=this.player.getVideoContentRect();if(R&&R.width!==0&&R.height!==0){var l=this.player.getPlayerSize();if(l&&l.width!==0&&l.height!==0){var y=R.width/R.height;var f=0;for(var A=-1,K=0;K<FJ5.length;K++){var G=Math.abs(l.width-FJ5[K]);if(A===-1||f>=G)A=K,f=G}f=QfU[A];this.L&&g.Df(this.L.element,"outline-width",Math.max(l.width,l.height)+"px");for(l=0;l<this.endscreen.elements.length;++l)if(K=this.endscreen.elements[l].id,A=this.X[K],
G=this.D[K],A&&G){var B=G.width*y/G.aspectRatio,H=Math.round(G.width*R.width);K=Math.round(B*R.height);var n=R.left+Math.round(G.left*R.width),m=R.top+Math.round(G.top*R.height);g.Rm(A.element,H,K);g.qh(A.element,n,m);g.ac(A.element,$St);H>256||K>256?g.AU(A.element,"ytp-ce-large-round"):H>96||K>96?g.AU(A.element,"ytp-ce-medium-round"):g.AU(A.element,"ytp-ce-small-round");g.ac(A.element,e3O);H=G.left+G.width/2;G=G.top+B/2;g.AU(A.element,H<=.5&&G<=.5?"ytp-ce-top-left-quad":H>.5&&G<=.5?"ytp-ce-top-right-quad":
H<=.5&&G>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ac(A.element,QfU);g.AU(A.element,f);(A=g.GP(document,"div","ytp-ce-expanding-overlay-body",A.element)[0])&&g.Df(A,"height",K+"px")}}}}};
g.L.onCueRangeEnter=function(R){if(this.endscreen)if(R.getId()==="ytp-ce-in-endscreen")DM(this,this.endscreen.impressionUrls),(R=g.Py())&&this.endscreen.visualElement&&g.Y$(R,this.endscreen.visualElement),this.Z&&(g.AU(this.Z,"ytp-ce-element-show"),this.Z.removeAttribute("aria-hidden"),this.player.LW()?g.AU(this.Z,"ytp-ce-hide-button-lower"):g.G8(this.Z,"ytp-ce-hide-button-lower"));else{R=R.getId().substring(15);var l=this.X[R],y=this.D[R];g.AU(l.element,"ytp-ce-element-show");l.element.removeAttribute("aria-hidden");
l=this.player.getRootNode();g.AU(l,"ytp-ce-shown");DM(this,y.impressionUrls);(l=g.Py())&&g.Y$(l,y.visualElement);this.player.U().W&&this.player.KX("endscreenelementshown",R)}};
g.L.onCueRangeExit=function(R){if(R.getId()==="ytp-ce-in-endscreen")this.Z&&(g.G8(this.Z,"ytp-ce-element-show"),this.Z.setAttribute("aria-hidden","true"));else{R=R.getId().substring(15);var l=this.X[R];g.G8(l.element,"ytp-ce-element-show");l.element.setAttribute("aria-hidden","true");l=this.player.getRootNode();g.G8(l,"ytp-ce-shown");this.player.U().W&&this.player.KX("endscreenelementhidden",R)}};
g.L.e0E=function(R){var l=this;R.target===window&&(new g.Vg(function(){for(var y=g.u(Object.values(l.X)),f=y.next();!f.done;f=y.next())g.ac(f.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.L.UF=function(R){for(var l=g.u(Object.values(this.X)),y=l.next();!y.done;y=l.next())y=y.value,R?y.element.setAttribute("hidden",""):y.element.removeAttribute("hidden")};
g.L.KeE=function(R){this.Z&&this.player.getRootNode().removeChild(this.Z);R&&(g.AU(R,"ytp-ce-hide-button-container"),this.Z=R,g.kT(this.player,this.Z,4))};
var FJ5=[346,426,470,506,570,640,853,1280,1920],QfU="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),e3O=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],$St=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var WWO={kg4:"current",gIb:"new"};var ODA={CLOSE:"close",oIQ:"openUrl",SUBSCRIBE:"subscribe"},iDU={nvb:"click",CLOSE:"close",lyb:"hidden",JzE:"rollOut",R34:"rollOver",oyx:"shown"};u9d.prototype.Jk=function(){var R=FW8(this,function(l){return l.type==="openUrl"&&l.url!=null});
return R?R.url:null};
var iY8={WW7:"anchored",Co:"branding",CHANNEL:"channel",u3Q:"cta",Mv$:"highlightText",hbL:"label",PLAYLIST:"playlist",POPUP:"popup",Omb:"speech",SUBSCRIBE:"subscribe",rzL:"title",VIDEO:"video",Af$:"website"},OYr={Co:"branding",sJx:"card",X69:"drawer",BN4:"highlight",qUQ:"marker",i7E:"promotion",TEXT:"text",xH9:"widget"};g.O(t8,g.p);g.L=t8.prototype;g.L.addCueRange=function(R,l,y,f,A){R=new g.Jq(R,l,{id:y,namespace:"annotations_module"});f&&this.UL.set(R,f);A&&this.tU.set(R,A);this.context.G.OS([R],1)};
g.L.Bu=function(){this.context.X.subscribe("resize",this.Sz,this)};
g.L.al=function(){return this.element};
g.L.Mt=function(R,l,y,f,A,K){if(this.B1)return!1;K&&(K.stopPropagation(),K.preventDefault());this.navigate(R,y,f,A);return!1};
g.L.show=function(){};
g.L.hide=function(){};
g.L.destroy=function(){g.Ot(this.al())};
g.L.Sz=function(){};
g.L.navigate=function(R,l,y,f){var A=this,K=J8(R);if(K){var G=d2S(K,R.target),B=function(){R.Z&&A.context.G.pauseVideo();var H=A.context.videoData.nJ||!1,n=g.f0(K||"");H&&n&&(n.v||n.list)?A.context.G.MA(n.v,l,n.list,!1):g.ki(K||"",G==="current"?"_top":void 0,l)};
G==="new"&&(B(),B=null);Bc(this.context.logger,y,B,f);TtK(K)||(y=g.Py(),f=l.itct,y&&f&&g.l1(y,g.Ll(f)))}};
g.L.G4=function(){this.UL.clear();this.tU.clear();g.p.prototype.G4.call(this)};
g.L.createElement=function(R){R=new g.Z(R);g.U(this,R);return R.element};g.O(v9U,t8);g.L=v9U.prototype;g.L.f7=function(){this.Yb&&ff(this,this.Yb)};
g.L.isAvailable=function(){var R;if(R=!!this.cards.length)(R=this.G.getRootNode())?(R=g.l4(R),R=173<R.width&&173<R.height):R=!1;return R};
g.L.Sz=function(){var R=this.isAvailable();g.yT(this.al(),R);g.BJ(this.context.G.getRootNode(),g.nA.IV_DRAWER_ENABLED,R);Ti(this.G)};
g.L.destroy=function(){this.G.G7(!1);try{this.G.getRootNode().removeChild(this.Y)}catch(R){}g.lq(this.LX);g.Xr(this.v1);this.jS&&this.jS.dispose();this.J&&this.J.dispose();t8.prototype.destroy.call(this)};
g.L.vx=function(){var R=this;this.context.Z.listen(g.aA("iv-drawer-close-button",this.Y),"click",this.ey,this);this.context.Z.listen(this.X,"touchend",function(){R.Dq.start()});
this.context.Z.listen(this.X,"scroll",this.Mp,this);this.context.X.subscribe("onHideControls",function(){R.CX=!0});
this.context.X.subscribe("onShowControls",function(){R.CX=!1});
this.context.X.subscribe("onVideoAreaChange",function(){R.CX=g.fg(R.G.getRootNode(),"ytp-autohide")});
this.LX.push(g.Rn("iv-button-shown",this.Sm,this));this.LX.push(g.Rn("iv-button-hidden",this.kN,this));U2Z(this)};
g.L.findLastIndex=function(R){if(this.cards.length===0)return 0;var l=g.P8(this.cards,function(y){return R.gx.startMs>y.gx.startMs||R.gx.startMs===y.gx.startMs&&R.gx.timestamp>=y.gx.timestamp?!0:!1});
return l===-1?0:l+1};
g.L.ey=function(){if(this.L){Bc(this.context.logger,G7(this).Ic.close);var R=g.Py();R&&this.V&&g.l1(R,this.V);l9(this)}};
g.L.Mp=function(){g.BJ(this.Y,"iv-drawer-scrolled",this.X.scrollTop>0)};
g.L.Sm=function(){var R=g.Py(),l=G7(this);l=l?l.U9:this.U9;R&&l&&g.MJ(R,[l])};
g.L.kN=function(){var R=g.Py(),l=G7(this);l=l?l.U9:this.U9;R&&l&&g.RN(R,[l])};
g.L.Sf=function(){var R=G7(this);Bc(this.context.logger,R.Ic.ws);var l=g.Py();if(l&&R)if(this.G.C("web_infocards_teaser_show_logging_fix")){var y=[];R.lE&&y.push(R.lE);R.U9&&y.push(R.U9);y.length>0&&g.MJ(l,y)}else g.MJ(l,[R.lE,R.U9])};
g.L.le=function(){var R=g.Py(),l=G7(this);R&&l&&g.RN(R,[l.lE])};
g.L.u0=function(R){var l=G7(this),y=g.Py();this.Z?R?(R=this.context.logger,Bc(R,l.Ic.y7),R.G.sendVideoStatsEngageEvent(4,void 0),y&&l.lE&&g.l1(y,l.lE)):(R=this.context.logger,Bc(R,l.Ic.y7),R.G.sendVideoStatsEngageEvent(4,void 0),y&&l.U9&&g.l1(y,l.U9)):(R=this.context.logger,Bc(R,l.Ic.y7),R.G.sendVideoStatsEngageEvent(4,void 0),y&&this.U9&&g.l1(y,this.U9))};g.O(aH,t8);aH.prototype.Bu=function(){t8.prototype.Bu.call(this);g9K(this)};
aH.prototype.show=function(){t8.prototype.show.call(this);var R=g.Py(),l=this.annotation.data;R&&l&&(l=l.session_data)&&g.MJ(R,[g.Ll(l.itct)])};
aH.prototype.hide=function(){t8.prototype.hide.call(this);var R=g.Py(),l=this.annotation.data;R&&l&&(l=l.session_data)&&g.RN(R,[g.Ll(l.itct)])};g.O(sc,aH);
sc.prototype.show=function(){if(!this.isActive){aH.prototype.show.call(this);if(!this.V){g.AU(this.al(),"iv-branding");var R=this.annotation.data;this.X=this.createElement({T:"img",QL:["branding-img","iv-click-target"],K:{"aria-label":"\ucc44\ub110 \uc6cc\ud130\ub9c8\ud06c",src:R.image_url,width:R.image_width,height:R.image_height}});g.yT(this.X,!1);var l=this.createElement({T:"button",QL:["branding-img-container","ytp-button"]});l.appendChild(this.X);this.al().appendChild(l);var y=this.annotation.Jk();y&&
Yd(this,l,y,this.annotation.id,R.session_data);this.context.G.C("disable_branding_context")||t4D(this,R);this.V=!0}g.yT(this.al(),!0);this.isActive=!0;if(this.X){try{V4Z(this,this.X)}catch(f){}g.AU(this.context.G.getRootNode(),"ytp-branding-shown");this.context.G.getRootNode().style.setProperty("--branding-image-width",this.X.getAttribute("width")+"px")}}};
sc.prototype.hide=function(){this.isActive&&(aH.prototype.hide.call(this),g.yT(this.al(),!1),this.isActive=!1,g.G8(this.context.G.getRootNode(),"ytp-branding-shown"))};
sc.prototype.destroy=function(){this.Z&&(this.Z.dispose(),this.Z=null);g.G8(this.context.G.getRootNode(),"ytp-branding-shown");aH.prototype.destroy.call(this)};g.O(M4U,aH);g.L=M4U.prototype;g.L.show=function(){this.isActive||(aH.prototype.show.call(this),this.B||(laU(this),this.B=!0),g.yT(this.al(),!0),g.N_(function(){g.G8(this.al(),"iv-promo-inactive")},100,this),this.al().removeAttribute("aria-hidden"),this.isActive=!0,KJA(this),yb5(this),faK(this,this.D))};
g.L.hide=function(){this.isActive&&(g.AU(this.al(),"iv-promo-inactive"),this.isActive=!1,this.al().setAttribute("aria-hidden","true"))};
g.L.Mt=function(R,l,y,f,A,K){return this.isCollapsed?!1:aH.prototype.Mt.call(this,R,l,y,f,A,K)};
g.L.A0=function(R){this.W=!0;R3K(this,500,R)};
g.L.NR=function(){this.W=!1;AbU(this)};
g.L.vD=function(R){R.stopPropagation();this.hide()};
g.L.fp=function(R){R.stopPropagation();KJA(this);this.isCollapsed=!0;g.AU(this.al(),"iv-promo-collapsed-no-delay");this.J.start()};
g.L.destroy=function(){this.J.dispose();aH.prototype.destroy.call(this)};g.O(aaA,g.Fc);g.L=aaA.prototype;g.L.MD=function(R,l){if(!u7X(this.player.U().playerStyle))return null;switch(R){case "loadCustomAnnotationsXml":return(R=g.RC(l))&&mSZ(this,R),!0;case "removeCustomAnnotationById":return l&&this.Z&&(Ilr(this.Z,l),Ti(this.player)),!0}return null};
g.L.getOptions=function(){return u7X(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.L.S9=function(){var R=this.player.U(),l=this.player.getVideoData(),y=R.annotationsLoadPolicy||l.annotationsLoadPolicy;return g.Bd(l)||this.player.isMutedByEmbedsMutedAutoplay()?!1:y===1&&!l.G_||R.CX.get(l.videoId)||g.gI(l)||g.VE(l)?!0:!1};
g.L.hS=function(){if(this.L){var R=this.player.lQ().getVideoContentRect(!0);g.Rm(this.L.element,R.width,R.height);g.qh(this.L.element,R.left,R.top)}if(this.Z){var l=this.player.vQ();R=this.Z;l=l.width;g.BJ(R.Y,"iv-drawer-small",l<=426);g.BJ(R.Y,"iv-drawer-big",l>=1280)}};
g.L.l0=function(R){Bk5(this,R.state);g.V(R.state,2)&&(this.LW()&&this.VW()&&this.player.getPresentingPlayerType()!==2&&this.a_(!1),this.G7(!1))};
g.L.load=function(){function R(G){var B=l.loadNumber;l.J=null;l.loaded&&l.loadNumber===B&&l.player.getVideoData().videoId===f&&(G=g.ow(G)&&G.responseXML?G.responseXML:null)&&(mSZ(l,G),g.AU(l.player.getRootNode(),"iv-module-loaded"))}
var l=this;g.Fc.prototype.load.call(this);Bk5(this,this.player.getPlayerStateObject());this.loadNumber++;var y=this.player.getVideoData(),f=y.videoId;g.Rq()&&(R=oG5(this,R));var A={format:"XML",onFinish:R,onError:function(){l.J=null},
urlParams:{}};y.isPharma&&(A.urlParams.pharma="1");A.method="POST";A.withCredentials=!0;var K=this.player.U().CX.get(f);K&&h3r(A,K);K=K&&(K.Qt||K.rl);if(!y.IB||K)y.v1?HYA(this,y.v1,A):(this.V=function(){if(!l.W)l.onVideoDataChange(A);var G=l.player.getVideoData();(G==null?0:g.Jt(G))&&!l.LX&&LJD(l,G)},this.player.addEventListener("videodatachange",this.V));
g.kT(this.player,this.L.element,4);this.hS();(K=g.gI(y))&&WJU(this,K);(K=g.VE(y))&&K.featuredChannel&&PTA(this,K.featuredChannel,K.annotationId||"branding",y.videoId||null,y.eventId||null);this.Ls=g.aA("ytp-cards-button",this.player.getRootNode());g.Jt(y)&&LJD(this,y)};
g.L.onVideoDataChange=function(R){var l=this.player.getVideoData();l.v1&&HYA(this,l.v1,R)};
g.L.unload=function(){this.player.yb("annotations_module");for(var R=g.u(Object.keys(this.D)),l=R.next();!l.done;l=R.next())this.D[l.value].destroy();this.B=null;this.Z&&(this.Z.destroy(),this.Z=null,Ti(this.player));this.W=!1;this.J&&(this.J.abort(),this.J=null);this.LX=!1;this.D={};this.X.hide();g.Fc.prototype.unload.call(this);this.L.detach();this.V&&(this.player.removeEventListener("videodatachange",this.V),this.V=null)};
g.L.aX=function(R){R===this.player.getVideoData().videoId&&(this.loaded?cb8(this):this.load())};
g.L.LW=function(){var R;return((R=this.Z)==null?void 0:R.isAvailable())||this.LX};
g.L.VW=function(){return!!this.Z&&this.Z.L};
g.L.a_=function(R,l,y){l=l===void 0?!1:l;this.LW();this.Z&&(R?y?RH(this.Z,y,l):RH(this.Z,"YOUTUBE_DRAWER_AUTO_OPEN",l):l9(this.Z))};
g.L.G7=function(R,l){this.player.publish(R?"cardsteasershow":"cardsteaserhide",l)};
g.L.G4=function(){this.player.U().CX.unsubscribe("vast_info_card_add",this.aX,this);g.G8(this.player.getRootNode(),g.nA.IV_DRAWER_OPEN);for(var R=this.Yb,l=g.pz,y=0,f=R.length;y<f;y++)l.Yz(R[y]);this.Yb.length=0;g.Fc.prototype.G4.call(this)};
g.L.createElement=function(R){R=new g.Z(R);g.U(this,R);return R.element};g.uR("annotations_module",aaA);g.uR("creatorendscreen",yar);})(_yt_player);
